[h1]Jango's Update[/h1]
[h2]Custom Gear[/h2]
[h3]Added[/h3]
[list]
    [*] Clone Trooper armor (104th Squid)
    [*] Clone Trooper armor (104th Poet)
[/list]
[h3]Removed[/h3]
[list]
    [*] 
[/list]
[h3]Changes[/h3]
[list]
    [*] Clone ARC Trooper Vest (104th Drifter)
    [*] Clone Trooper ARC Trooper Helmet (104th Drifter)
    [*] Clone Trooper armor (104th Drifter)
[/list]

[h2]Custom Weapons & Attachments[/h2]
[h3]Added[/h3]
[list]
    [*] 
[/list]
[h3]Removed[/h3]
[list]
    [*] 
[/list]
[h3]Changes[/h3]
[list]
    [*] 
[/list]

[h2]Custom Vehicles & Supplies[/h2]
[h3]Added[/h3]
[list]
    [*] 
[/list]
[h3]Removed[/h3]
[list]
    [*] 
[/list]
[h3]Changes[/h3]
[list]
    [*] 
[/list]
