import os;
import re;

files = os.listdir("./Assets/PAA.tocode")
for file in files:
    oldname = file
    print(oldname)
    file=file.replace("_p2_","_P2_")
    file=file.replace("_ab_","_AB_")
    file=file.replace("_p1_","_P1_")
    file=file.replace("_arc_","_ARC_")
    file=file.replace("_pilot","_Pilot")
    file=file.replace("_barc","_BARC")
    file=file.replace("_jtac","_JTAC")
    file=file.replace("_arf_","_ARF_")
    
    file=file.replace("_lower","_Lower")
    file=file.replace("_upper","_Upper")
    file=file.replace("_helmet","_Helmet")
    file=file.replace("_officer","_Officer")
    file=file.replace("_nvg","_NVG")
    file=file.replace("_kama","_Kama")
    file=file.replace("_light","_Light")
    file=file.replace("_jumppack","_Jumppack")
    file=file.replace("_backpack","_Backpack")
    file=file.replace("_lifesupport","_Lifesupport")
    file=file.replace("_rangefinder","_Rangefinder")
    file=file.replace("_accessories","_Accessories")
    
    file=file.replace("_q","_Q")
    file=file.replace("_w","_W")
    file=file.replace("_e","_E")
    file=file.replace("_r","_R")
    file=file.replace("_t","_T")
    file=file.replace("_y","_Y")
    file=file.replace("_u","_U")
    file=file.replace("_i","_I")
    file=file.replace("_o","_O")
    file=file.replace("_p","_P")
    file=file.replace("_a","_A")
    file=file.replace("_s","_S")
    file=file.replace("_d","_D")
    file=file.replace("_f","_F")
    file=file.replace("_g","_G")
    file=file.replace("_h","_H")
    file=file.replace("_j","_J")
    file=file.replace("_k","_K")
    file=file.replace("_l","_L")
    file=file.replace("_ç","_Ç")
    file=file.replace("_z","_Z")
    file=file.replace("_x","_X")
    file=file.replace("_c","_C")
    file=file.replace("_v","_V")
    file=file.replace("_b","_B")
    file=file.replace("_n","_N")
    file=file.replace("_m","_M")

    print(file)
    if file.endswith(".paa"):
        os.rename("./Assets/PAA.tocode/"+oldname,"./Assets/PAA.tocode/"+file)