private _console = _this select 0;
private _vehicle = _this select 1;     
private _dir = getDir _console;
private _veh = createVehicle [_vehicle,[0,0,0],[],0,"NONE"];     
_veh setVehicleAmmo 1;      
_veh setDir _dir;
_veh setPosASL (_console modelToWorldWorld [15,0,1]);   
sleep 1;
_veh setDamage 0; 
sleep 1;
_veh setDamage 0; 
sleep 1;
_veh setDamage 0; 
sleep 1;
_veh setDamage 0; 
sleep 1;
_veh setDamage 0; 
sleep 1;
_veh setDamage 0; 
