private["_console","_vehicle","_dir","_veh"];
_console = _this select 0;
_vehicle = _this select 1;     
_dir = getDir _console;         
_veh = createVehicle [_vehicle,[0,0,0],[],0,"NONE"];     
_veh setVehicleAmmo 1;      
_veh setDir _dir;
_veh setPosASL (_console modelToWorldWorld [15,0,1]);   
sleep 1;
_veh setDamage 0; 
sleep 1;
_veh setDamage 0; 
sleep 1;
_veh setDamage 0; 
sleep 1;
_veh setDamage 0; 
sleep 1;
_veh setDamage 0; 
sleep 1;
_veh setDamage 0; 